# Generated by Django 4.2.3 on 2023-08-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('productora', models.CharField(max_length=50)),
                ('actor_protagonista', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('DRAMA', 'Drama'), ('ACCION', 'Acción'), ('AVENTURA', 'Aventura'), ('COMEDIA', 'Comedia'), ('TERROR', 'Terror'), ('OTROS', 'Otros')], max_length=20)),
                ('fecha_estreno', models.DateField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Videojuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('productora', models.CharField(max_length=50)),
                ('actor_protagonista', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('FPS', 'FPS'), ('ACCION', 'Acción'), ('AVENTURA', 'Aventura'), ('ESTRATEGIA', 'Estrategia'), ('TERROR', 'Terror'), ('OTROS', 'Otros')], max_length=20)),
                ('fecha_estreno', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('consolas', models.CharField(choices=[('PLAYSTATION_4', 'PlayStation 4'), ('PLAYSTATION_5', 'PlayStation 5'), ('NINTENDO_SWITCH', 'Nintendo Switch'), ('XBOX_ONE', 'Xbox One'), ('PC', 'PC'), ('OTROS', 'Otros')], max_length=20)),
            ],
        ),
    ]
